name: hello-wallx # you probably want to 'snapcraft register <name>'
# base: core18 # the base snap is the execution environment for this snap
version: '2.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: GNU Hello, the "hello world" snap # 79 char long summary
description: |
  GNU hello prints a greeting.

grade: stable # devel # must be 'stable' to release into candidate/stable channels
confinement: strict # devmode # use 'strict' once you have the right plugs and slots


apps:
 hello:
  command: bin/hello
 bash:
  command: bash


parts:
 gnu-hello:
  source: http://ftp.gnu.org/gnu/hello/hello-2.10.tar.gz
  plugin: autotools
 gnu-bash:
  source: http://ftp.gnu.org/gnu/bash/bash-4.3.tar.gz
  plugin: autotools
  configflags: ["--infodir=/var/bash/info"]






